### ISSUE TITLE
Crash when sugar cane breaks and lands on water

### ISSUE THREAD

**Issue by Mewtwoy** [StrikerRockers-Mods/VanillaTweaksFabric#1]
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property class_2754{name=half, clazz=class net.minecraft.class_2756, values=[upper, lower]} as it does not exist in Block{minecraft:water}
    at net.minecraft.state.State.get(State:95)
    at net.minecraft.block.TallPlantBlock.canPlaceAt(TallPlantBlock:66)
    at net.minecraft.entity.ItemEntity.handler$bcc002$tick(ItemEntity:1059)
    at net.minecraft.entity.ItemEntity.tick(ItemEntity:95)
    at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:621)
    at net.minecraft.class_3218$$Lambda$7526/2059145733.accept(Unknown Source)
    at net.minecraft.world.World.tickEntity(World:561)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld:411)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
    at net.minecraft.server.MinecraftServer$$Lambda$7209/1283203608.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

**Comment by strikerrocker** [comment]
Looking into it

**Comment by strikerrocker** [comment]
Releasing an new version now.

**Comment by strikerrocker** [comment]
Hey currently the file is in for cf moderation looking at their new working times its gonna be 12hours from now. Join the discord and i will give a quick fix

**Comment by strikerrocker** [comment]
Forgot to add the link. https://discord.gg/tqcqeSj

**Comment by strikerrocker** [comment]
CF approved the file https://www.curseforge.com/minecraft/mc-mods/vanillatweaks-fabric/files/3138703
