### ISSUE TITLE
Crash when multiple blocks are broken using tool with Siphon

### ISSUE THREAD

**Issue by Mewtwoy** [StrikerRockers-Mods/VanillaTweaksFabric#2]
Description: Ticking entity

java.lang.UnsupportedOperationException
    at java.util.Collections$SingletonList.removeIf(Collections.java:4826)
    at io.github.strikerrocker.vt.enchantments.SiphonEnchantment.siphonLogic(SiphonEnchantment.java:21)
    at net.minecraft.block.Block.handler$bcc000$dropLoot(Block:3094)
    at net.minecraft.block.Block.getDroppedStacks(Block:325)
    at net.minecraft.block.Block.dropStacks(Block:351)
    at net.minecraft.block.Block.afterBreak(Block:402)
    at net.minecraft.server.network.ServerPlayerInteractionManager.tryBreakBlock(ServerPlayerInteractionManager:268)
    at net.minecraft.server.network.ServerPlayerInteractionManager.update(ServerPlayerInteractionManager:103)
    at net.minecraft.server.network.ServerPlayerEntity.tick(ServerPlayerEntity:379)
    at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:621)
    at net.minecraft.class_3218$$Lambda$7579/2018282440.accept(Unknown Source)
    at net.minecraft.world.World.tickEntity(World:561)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld:411)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
    at net.minecraft.server.MinecraftServer$$Lambda$7263/1651168539.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

**Comment by strikerrocker** [comment]
Looking into it

**Comment by strikerrocker** [comment]
What block did you break? Can i get the game log if possible? Also can i get the exact description of what happened as i am not able to reproduce this my breaking multiple blocks with the pickaxe.

**Comment by Mewtwoy** [comment]
Seems to be a partial incompatibility with BetterNether and BetterEnd mods, most blocks mined using a tool with siphon will give zero drops.
Was able to reproduce the crash after a few tries by mining "Violecite", from the BetterEnd mod.

**Comment by strikerrocker** [comment]
Hey can you hop on discord so i can give you an test version?
Ping me

**Comment by strikerrocker** [comment]
discord link : https://discord.gg/tqcqeSj
