### ISSUE TITLE
Datapack Loading Errors when features disabled

### ISSUE THREAD

**Issue by IdrisQe** [StrikerRockers-Mods/VanillaTweaksFabric#3]
When features that add items or blocks that are craftable are disabled in 1.0.6 (1.16.5), trying to create a new world crashes, picked up by Not Enough Crashes, for each item as it tries to load recipes for items that don't exist.

![image](https://user-images.githubusercontent.com/40530630/109405505-100df380-7926-11eb-9de3-f6c66dc92f3e.png)

An example, with the Fried Egg disabled:
```
[17:59:39] [main/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Item: vanillatweaks:fried_egg does not exist
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1959) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1808) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29607(MinecraftClient:1752) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen:298) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen:238) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:33) ~[?:?]
	at net.minecraft.client.gui.widget.AbstractPressableButtonWidget.onClick(AbstractPressableButtonWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.AbstractButtonWidget.mouseClicked(AbstractButtonWidget:149) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:92) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:435) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:162) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:162) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:127) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1071) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Item: vanillatweaks:fried_egg does not exist
	at net.minecraft.recipe.CookingRecipeSerializer.method_17879(CookingRecipeSerializer:33) ~[?:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.recipe.CookingRecipeSerializer.read(CookingRecipeSerializer:33) ~[?:?]
	at net.minecraft.recipe.CookingRecipeSerializer.read(CookingRecipeSerializer:11) ~[?:?]
	at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager:123) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:54) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18790(SinglePreparationResourceReloadListener:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1958) ~[?:?]
	... 36 more
```

**Comment by strikerrocker** [comment]
Fixed there already thus closing
